# Generated by Django 5.1 on 2024-08-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_HN', models.AutoField(primary_key=True, serialize=False)),
                ('patient_IDcard', models.CharField(max_length=13)),
                ('patient_firstName', models.CharField(max_length=255)),
                ('patient_lastName', models.CharField(max_length=255)),
                ('patient_birthdate', models.DateField()),
                ('patient_UD', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
