# Generated by Django 5.1.1 on 2024-09-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_alter_patient_patient_ud'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_prefix',
            field=models.CharField(choices=[('Mr', 'นาย'), ('Ms', 'นางสาว'), ('Mrs', 'นาง')], default='Mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_IDcard',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
