# Generated by Django 5.1.1 on 2024-09-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'ผู้ป่วย', 'verbose_name_plural': 'รายขื่อผู้ป่วย'},
        ),
    ]
