# Generated by Django 5.1.1 on 2024-09-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0006_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
