# Generated by Django 5.1.1 on 2024-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0008_alter_patient_options'),
        ('app_underlying_disease', '0004_alter_underlyingdisease_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_UD',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_UD',
            field=models.ManyToManyField(blank=True, to='app_underlying_disease.underlyingdisease'),
        ),
    ]
