# Generated by Django 5.1 on 2024-08-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderlyingDisease',
            fields=[
                ('UD_no', models.AutoField(primary_key=True, serialize=False)),
                ('nameUD', models.CharField(max_length=255)),
            ],
        ),
    ]
