# Generated by Django 5.1.1 on 2024-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_underlying_disease', '0003_alter_underlyingdisease_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='underlyingdisease',
            options={'verbose_name': 'โรคประจำตัว', 'verbose_name_plural': 'ชื่อโรคประจำตัว'},
        ),
    ]
