# Generated by Django 5.1 on 2024-08-28 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_general', '0002_alter_patient_patient_ud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Ddx', models.CharField(max_length=255)),
                ('MRI_pic', models.ImageField(blank=True, null=True, upload_to='uploaded_images/')),
                ('recommend', models.TextField()),
                ('patient_HN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.patient')),
            ],
            options={
                'unique_together': {('patient_HN', 'date')},
            },
        ),
    ]
