# Generated by Django 5.1.1 on 2024-09-10 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
