# Generated by Django 5.1.1 on 2024-09-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diagnostic', '0002_alter_diagnostic_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name': 'การวินิจฉัย', 'verbose_name_plural': 'ประวัติการวินิจฉัย'},
        ),
    ]
