# Generated by Django 5.1.1 on 2024-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diagnostic', '0003_alter_diagnostic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='MRI_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='recommend',
            field=models.TextField(max_length=500),
        ),
    ]
